---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# rpasswordgen

<!-- badges: start -->
<!-- badges: end -->

The goal of rpasswordgen is to generate one or multiple secure passwords

## Installation

You can install the development version of rpasswordgen from [GitHub](https://github.com/djazq/rpasswordgen) with:

``` r
# install.packages("remotes")
remotes::install_github("djazq/rpasswordgen")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(rpasswordgen)
## basic example code
# Generate a 12-character password with only lowercase and numbers
generate_password(12, use_upper = FALSE, use_lower = TRUE, use_numbers = TRUE, use_special = FALSE)
# Generate 3 passwords, each 12 characters long with only lowercase and numbers
generate_multiple_passwords(3, 12, use_upper = FALSE, use_lower = TRUE, use_numbers = TRUE, use_special = FALSE)
```
